<!-- This file is automatically generated. Please do not edit this file, changes will be overwritten by a next build. -->

<?php
  $colors = (object) [
<% var i=0; Object.keys(colors).forEach(function(color){ i++; -%>
  '<%= _.camelCase(colors[color].name) %>' => '<%= colors[color].hex %>'<% if (i < Object.keys(colors).length){ %>,<% } %> 
<% }); %>
  ];
  
  <% if(settings.rgb) { -%>
  $colors_rgb = (object) [
<% var i=0; Object.keys(colors).forEach(function(color){ i++; -%>
  '<%= _.camelCase(colors[color].name) %>' => [<%= colors[color].rgb.r %>, <%= colors[color].rgb.g %>, <%= colors[color].rgb.b %>]<% if (i < Object.keys(colors).length){ %>,<% } %> 
<% }); %>
  ];<% } %>

  <% if(settings.hsl) { -%>
  $colors_hsl = (object) [
<% var i=0; Object.keys(colors).forEach(function(color){ i++; -%>
  '<%= _.camelCase(colors[color].name) %>' => [<%= _.toRoundNumber(colors[color].hsl.h) %>, <%= _.toRoundNumber(colors[color].hsl.s) %>, <%= _.toRoundNumber(colors[color].hsl.l)%>]<% if (i < Object.keys(colors).length){ %>,<% } %> 
<% }); %>
  ];<% } %>
?>